# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode 14.3
      run: sudo xcode-select -s /Applications/Xcode_14.3.app
    - name: Build
      run: swift build --package-path BibleCore
    - name: Run tests
      run: swift test --package-path BibleCore
